version: '3.7'

services:
  ra-debuguer:
    image: ra-debugguer:1.0
    networks: 
      - app_net
  ra-site:
    image: ra-site:1.6.0
    networks:  
      - app_net
    ports:
      - "4200:80"
    deploy:
      replicas: 1
    configs:
      - source: apiUrljson
        target: /usr/share/nginx/html/assets/apiUrl.json
  ra-api:
    image: ra-api:1.2
    networks:  
      - app_net
    ports:
      - "4300:80"
    secrets:  
      - db_connect
    deploy:
      replicas: 1

networks:
  app_net:
    driver:   overlay

secrets:
  db_connect:
    file: ./ra-api/sql_connect.txt

configs:
  apiUrljson:
    file: ./ra-site/apiUrl.json